config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    resources :students
    resources :periods
    resources :notes
  end

   root 'users#index'

end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :students
  belongs_to :teacher
  has_many :notes
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
    @user = User.find(params[:user_id])
    @period = @user.periods.find(params[:id])
    @students = Student.find_by(class_id: params[:id])
    render :show
  end



  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period.destroy
    respond_to do |format|
      format.html { redirect_to periods_url, notice: 'Period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:name, :teacher_id, :period)
    end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<%= form_for(@period) do |f| %>
  <% if @period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% @period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.number_field :teacher_id %>
  </div>
  <div class="field">
    <%= f.label :period %><br>
    <%= f.number_field :period %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/periods/edit.html.erb
<h1>Editing Period</h1>

<%= render 'form' %>

<%= link_to 'Show', @period %> |
<%= link_to 'Back', periods_path %>

app/views/periods/index.html.erb
<p id="notice"><%= notice %></p>
<div class='center'>
<h3>Periods</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Period</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
<%= link_to 'Show', user_period_path[@user.periods, @period] %> </td>
        <td>
        <td><%= period.period %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/periods/new.html.erb
<h1>New Period</h1>

<%= render 'form' %>

<%= link_to 'Back', periods_path %>

app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @period.name %>
</p>


<p>
  <strong>Period:</strong>
  <%= @period.period %>
</p>


<% if @students %>
  <% if @students.class_id == params[:id]%>
    <% @students.each do |student| %>
    <tbody>
        <tr>

            <th><%= student.fname %></th>
            <td><%= student.lname %></td>

            <td><a href="/profiles/<%=@user.id%>/students/<%= student.id %>/edit" class= "editLink">Edit </a>
            </td>
            <td>
                <form id="noteList" action="/profiles/<%=@user.id%>/students/<%= student.id %>" method="POST">
                  <input type='hidden' name='_method' value='delete'>
                  <input class="deleteNote" type="submit" value="delete">
                </form>
            </td>
      </tr>
    </tbody>
    <% end %>
  <%end %>
<%end %>
</table>