config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    resources :students
    resources :periods
    resources :notes
  end

   root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :remember_token
  has_secure_password
  has_many :students
  has_many :notes
  has_many :periods

  before_save { self.email = email.downcase }
  validates :fname,  presence: true, length: { maximum: 50 }
  validates :lname,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


def show
    @user = User.find(params[:id])
end

  def new
    @user = User.new
  end


# def create
#     @user = User.new(params[:user])
#     if @user.save
#       flash[:notice] = "You signed up successfully"
#       flash[:color]= "valid"
#     else
#       flash[:notice] = "Form is invalid"
#       flash[:color]= "invalid"
#     end
#     render "new"
#   end



# def create
#     @user = User.new(user_params)
#     # respond_to do |format|
#       if @user.save
#         # format.html {
#         redirect_to @user, notice: 'User was successfully created.'
#         # format.json { render :show, status: :created, location: @user }
#       else
#         # format.html {
#         render :new
#         # format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
#     # end #format.html/json
#   end

########################
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      flash[:danger] = "Incorrect email/password"
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    First Name<br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    Last Name
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    Email
    <%= f.text_field :email %>
  </div>
  <div class="field">
    Password
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
 <div id="index-banner" class="parallax-container indigo">
    <div class="parallax">
      <img src="/images/background1.jpg" />
    </div>
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">TalkingStick</h1>
        <div class="row center">
          <h5 class="header col s12 light">The home to organize parent communication</h5>
        </div>
        <div class="row center">
          <%= link_to 'Login', login_path, :class=> "btn-large waves-effect waves-light teal lighten-1" %>
          <%= link_to 'Signup', new_user_path, :class => "btn-large waves-effect waves-light teal lighten-1" %>
        </div>
        <br><br>
      </div>
    </div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up note-taking</h5>

            <p class="light">With TalkingStick's notes form you just input the information in the correct spots and the rest is done for you!</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By providing your notes in a chart form allowing you to quickly reference a specific note.  Graphs allow you to see recent communication </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">Easily access previous notes to update when needed.</p>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Sticks in a bundle cannot be broken</h5>
        </div>
      </div>
    </div>
    <div class="parallax">
      <img_tag "images/background2.jpg">
    </div>
  </div>




  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">About Me</h5>
          <p class="grey-text text-lighten-4">As a former educator, I am dedicated to creating tools to help create more efficient systems so teachers can focus on what really matters, our students.</p>


        </div>

        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="wwww.linkedin.com/in/teresanesteby">LinkedIn</a></li>
            <li><a class="white-text" href="www.github.com/teresanesteby">GitHub</a></li>
          </ul>
        </div>
      </div>
    </div>

  </footer>

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="../../dist/js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>

app/views/users/new.html.erb
<h4>Signup Today!</h4>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
  <p id="notice"><%= notice %></p>

<h5 class='center'>
  <strong>Welcome, <%= @user.fname %> </strong>
</h5>



 <!--  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
      <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
      <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
      <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
    </li>
  </ul> -->










<div class="col s12">
  Graphs

</div>
<div class="col s12">
  <%= @user.periods %>
  <% if @user.periods %>
    <% @user.periods.each do |period| %>
  <div class="col s3">
     <p> Period <%= period.period %>


    <a class="btn-floating btn-large waves-effect waves-light indigo" ><%= link_to 'Show Period', user_period_path(@user, period) %><i class="material-icons">
    </i></a>
</p>
  </div>

<% end %>
<% end %>


<div class="col s6">
   <table class="highlight center responsive-table">
    <%= @user.notes %>



    <thead>
        <tr>
            <th></th>
            <th>Student</th>
            <th>Title</th>
            <th>Positive</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
<%= @user.notes %>
  <% if @user.notes %>
    <% @user.notes.each do |note| %>
    <tbody>
        <tr>

            <th><%= note.date %></th>
            <td><%= note.student %></td>
            <td><%= note.title %></td>
            <td><%= note.positive %></td>
            <td><a href="/profiles/<%=@user.id%>/notes/<%= note.id %>/edit" class= "editLink">Edit </a>
            </td>
            <td>
                <form id="noteList" action="/profiles/<%=@user.id%>/notes/<%= note.id %>" method="POST">
                  <input type='hidden' name='_method' value='delete'>
                  <input class="deleteNote" type="submit" value="delete">
                </form>
            </td>
      </tr>
    </tbody>
  <%end %>
<%end %>
</table>

<h5>Add your communication note below</h5>

<form action = "/profiles/<%=@user.id%>/notes" method = 'post' action="create" class = 'add_note' id = <%= @user.id %>>
  <input type= 'text' name = 'student' placeholder= 'student'>
  <input type= 'date' name = 'date_of_meeting' placeholder= 'date'>

  <input type= 'text' name = 'title' placeholder= 'title'>
  <input type= 'text' name = 'description' placeholder='description'>
   <div class="switch" name="positive">
    <label>
      Positive
      <input type="checkbox">
      <span class="lever"></span>
      Negative
    </label>
  </div>
  <input type= 'submit' value='Add Note' class="btn-large waves-effect waves-light indigo">
</form>

<table :hidden>
    <tbody class="note-template">
        <tr class="pure-table-odd">
            <th class='id'></th>
            <td class='student'></td>
            <td class='title'></td>
            <td class='positive'></td>
            <td><a href="" class= "note-edit">Edit </a></td>
            <td>
                <form action="" method="POST" class = "note-delete">
                    <input type='hidden' name='_method' value='delete'>
                    <input type="submit" value="delete">
                </form>
            </td>
      </tr>
    </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<%= link_to 'Edit', edit_user_path(@user) %> |